"""add defalut_provider column

迁移 ID: de4344fd6e4c
父迁移: 09e00213edc6
创建时间: 2025-11-24 23:40:30.045304

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "de4344fd6e4c"
down_revision: str | Sequence[str] | None = "09e00213edc6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("maimaidx_userbindinfo", schema=None) as batch_op:
        batch_op.add_column(sa.Column("default_provider", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("maimaidx_userbindinfo", schema=None) as batch_op:
        batch_op.drop_column("default_provider")

    # ### end Alembic commands ###
