from __future__ import annotations

from PIL import Image, ImageDraw

from ..score import PlayerMaiB50, PlayerMaiInfo
from .render_core import (
    BOT_LABEL,
    BestRatingMixin,
    MaimaiScorePainter,
    PIC_DIR,
    TBFONT,
    draw_rating_digits,
    footer_design,
    get_image,
    player_class_plate,
    player_icon_image,
    player_match_plate,
    player_plate_image,
    player_rating_plate,
    safe_font,
)


class DrawBest(BestRatingMixin):
    def __init__(self) -> None:
        self._name_font = safe_font(PIC_DIR.parent.parent / "ResourceHanRoundedCN-Bold.ttf", 25)
        self._formula_font = safe_font(TBFONT, 17)

    def draw(self, player_info: PlayerMaiInfo, best50: PlayerMaiB50) -> Image.Image:
        background_path = PIC_DIR / "b50_bg.png"
        image = get_image(background_path) if background_path.exists() else Image.new("RGBA", (1400, 1600), (255, 255, 255, 255))
        draw = ImageDraw.Draw(image)
        painter = MaimaiScorePainter(image)

        logo_path = PIC_DIR / "logo.png"
        if logo_path.exists():
            image.alpha_composite(get_image(logo_path).resize((249, 120)), (14, 60))

        image.alpha_composite(player_plate_image(player_info), (300, 60))
        image.alpha_composite(player_icon_image(player_info), (305, 65))

        rating_path = player_rating_plate(player_info.rating)
        if rating_path.exists():
            image.alpha_composite(get_image(rating_path).resize((186, 35)), (435, 72))
        draw_rating_digits(image, player_info.rating, (520, 80))

        name_path = PIC_DIR / "Name.png"
        if name_path.exists():
            image.alpha_composite(get_image(name_path), (435, 115))

        match_path = player_match_plate(player_info)
        if match_path and match_path.exists():
            image.alpha_composite(get_image(match_path).resize((80, 32)), (625, 120))

        class_path = player_class_plate(player_info)
        if class_path and class_path.exists():
            image.alpha_composite(get_image(class_path).resize((90, 54)), (620, 60))

        rainbow_path = PIC_DIR / "UI_CMN_Shougou_Rainbow.png"
        if rainbow_path.exists():
            image.alpha_composite(get_image(rainbow_path).resize((270, 27)), (435, 160))

        draw.text((445, 135), player_info.name, fill=(0, 0, 0, 255), font=self._name_font, anchor="lm")

        sd_rating, dx_rating = self.total_rating(best50)
        formula = f"B35: {sd_rating} + B15: {dx_rating} = {player_info.rating}"
        draw.text((570, 172), formula, fill=(255, 255, 255, 255), font=self._formula_font, anchor="mm", stroke_width=3, stroke_fill=(0, 0, 0, 255))

        painter.draw_cards(best50.standard[:35], 16, 235)
        painter.draw_cards(best50.dx[:15], 16, 1085)
        footer_design(image, f"Designed by Yuri-YuzuChaN & BlueDeer233. Generated by {BOT_LABEL}", bottom=113)
        return image
