from __future__ import annotations

from io import BytesIO
from math import ceil
from typing import Iterable, Sequence, Union

from PIL import Image

from ..functions.process import LevelProcessData, PlateProcessData, UnfinishedSong, _is_dx_plate
from ..score import PlayerMaiScore
from ..score._schema import ScoreFCType, ScoreFSType, ScoreRateType, SongDifficulty, SongType
from .render_core import (
    BOT_LABEL,
    MaimaiScorePainter,
    build_maimai_background,
    footer_design,
    not_played_grid,
    section_title,
)


class ProcessPainter:
    def __init__(self, data: Union[PlateProcessData, LevelProcessData]):
        self.data = data
        self.width = 1400

    def draw_plate(self, use_difficult: bool = False) -> BytesIO:
        if not isinstance(self.data, PlateProcessData):
            raise ValueError("Data must be PlateProcessData")

        is_dx = _is_dx_plate(self.data.ver_name)
        sections: list[tuple[str, list[PlayerMaiScore], list[tuple[int, int, str]]]] = []

        if use_difficult:
            sections.append(self._build_plate_section("高难剩余曲目", self.data.difficult_left, is_dx))
        else:
            buckets = [
                ("Basic 剩余", self.data.basic_left),
                ("Advanced 剩余", self.data.advanced_left),
                ("Expert 剩余", self.data.expert_left),
                ("Master 剩余", self.data.master_left),
                ("Re:Master 剩余", self.data.remaster_left),
            ]
            for title, items in buckets:
                if items:
                    sections.append(self._build_plate_section(title, items, is_dx))

        if not sections:
            image = build_maimai_background(self.width, 420)
            section_title(image, f"{self.data.ver_name}{self.data.plan} 已全部完成", y=30)
            footer_design(image, f"Designed by Yuri-YuzuChaN & BlueDeer233. Generated by {BOT_LABEL}", bottom=113)
            return self._to_bytes(image)

        height = 150
        for _, cards, not_played in sections:
            if cards:
                height += 140 + ceil(len(cards) / 5) * 114
            if not_played:
                height += 140 + ceil(len(not_played) / 20) * 65
        height += 120

        image = build_maimai_background(self.width, height)
        painter = MaimaiScorePainter(image)
        y = 30
        for title, cards, missing in sections:
            section_title(image, title, y=y)
            y += 110
            if cards:
                painter.draw_cards(cards, 16, y)
                y += ceil(len(cards) / 5) * 114 + 30
            if missing:
                y = not_played_grid(image, missing, start_y=y, title="未游玩谱面")
                y += 30

        footer_design(image, f"Designed by Yuri-YuzuChaN & BlueDeer233. Generated by {BOT_LABEL}", bottom=113)
        return self._to_bytes(image)

    def draw_level(self) -> BytesIO:
        if not isinstance(self.data, LevelProcessData):
            raise ValueError("Data must be LevelProcessData")

        completed = [score for _, score, _ in self.data.completed if score is not None]
        unfinished = [score for _, score, _ in self.data.unfinished if score is not None]
        not_played = [(song.id, diff_idx, song.title) for song, diff_idx in self.data.not_played]

        completed_rows = ceil(len(completed) / 5) if completed else 0
        unfinished_rows = ceil(len(unfinished) / 5) if unfinished else 0
        not_played_rows = ceil(len(not_played) / 20) if not_played else 0
        height = 150
        height += 140 + max(1, completed_rows) * 114
        height += 140 + max(1, unfinished_rows) * 114
        height += 140 + max(1, not_played_rows) * 65
        height += 120

        image = build_maimai_background(self.width, height)
        painter = MaimaiScorePainter(image)

        y = 30
        section_title(image, f"已完成谱面「{len(completed)}」个", y=y)
        y += 110
        if completed:
            painter.draw_cards(completed, 16, y)
            y += completed_rows * 114 + 30
        else:
            y += 30

        section_title(image, f"未完成谱面「{len(unfinished)}」个", y=y)
        y += 110
        if unfinished:
            painter.draw_cards(unfinished, 16, y)
            y += unfinished_rows * 114 + 30
        else:
            y += 30

        y = not_played_grid(image, not_played, start_y=y + 110, title=f"未游玩谱面「{len(not_played)}」个")
        footer_design(image, f"Designed by Yuri-YuzuChaN & BlueDeer233. Generated by {BOT_LABEL}", bottom=113)
        return self._to_bytes(image)

    def _build_plate_section(
        self,
        title: str,
        items: Sequence[UnfinishedSong],
        is_dx: bool,
    ) -> tuple[str, list[PlayerMaiScore], list[tuple[int, int, str]]]:
        cards: list[PlayerMaiScore] = []
        not_played: list[tuple[int, int, str]] = []
        for item in items:
            synthetic = self._synthetic_score(item, is_dx)
            if synthetic is None:
                not_played.append((item.song.id, item.difficulty, item.song.title))
            else:
                cards.append(synthetic)
        return title, cards, not_played

    def _synthetic_score(self, item: UnfinishedSong, is_dx: bool) -> PlayerMaiScore | None:
        status = item.status.lower()
        if status == "未游玩":
            return None

        achievements = 0.0
        fc = None
        fs = None
        if status.endswith("%"):
            try:
                achievements = float(status[:-1])
            except ValueError:
                achievements = 0.0
        elif status in {member.value for member in ScoreFCType}:
            achievements = 100.0
            fc = ScoreFCType(status)
        elif status in {member.value for member in ScoreFSType}:
            achievements = 100.0
            fs = ScoreFSType(status)

        diff = item.song.difficulties.dx[item.difficulty] if is_dx else item.song.difficulties.standard[item.difficulty]
        return PlayerMaiScore(
            song_id=item.song.id,
            song_name=item.song.title,
            song_type=SongType.DX if is_dx else SongType.STANDARD,
            song_level=diff.level,
            song_difficulty=SongDifficulty(item.difficulty),
            achievements=achievements,
            dx_score=0,
            dx_star=0,
            dx_rating=0.0,
            rate=self._rate_from_achievement(achievements),
            fc=fc,
            fs=fs,
            song_level_value=item.level_value,
        )

    @staticmethod
    def _rate_from_achievement(achievement: float) -> ScoreRateType:
        if achievement < 50:
            return ScoreRateType.D
        if achievement < 60:
            return ScoreRateType.C
        if achievement < 70:
            return ScoreRateType.B
        if achievement < 75:
            return ScoreRateType.BB
        if achievement < 80:
            return ScoreRateType.BBB
        if achievement < 90:
            return ScoreRateType.A
        if achievement < 94:
            return ScoreRateType.AA
        if achievement < 97:
            return ScoreRateType.AAA
        if achievement < 98:
            return ScoreRateType.S
        if achievement < 99:
            return ScoreRateType.SP
        if achievement < 99.5:
            return ScoreRateType.SS
        if achievement < 100:
            return ScoreRateType.SSP
        if achievement < 100.5:
            return ScoreRateType.SSS
        return ScoreRateType.SSSP

    @staticmethod
    def _to_bytes(image: Image.Image) -> BytesIO:
        bio = BytesIO()
        image.save(bio, format="PNG")
        bio.seek(0)
        return bio
