from __future__ import annotations

import math
from typing import List, Optional

from PIL import Image

from ..functions.recommend_songs import RecommendSongs
from ..score import PlayerMaiInfo, PlayerMaiScore
from .render_core import (
    BOT_LABEL,
    PIC_DIR,
    TEXT_COLOR,
    MaimaiScorePainter,
    build_maimai_background,
    footer_design,
    get_image,
    section_title,
)


class DrawScores:
    def __init__(self, image: Optional[Image.Image] = None) -> None:
        self._image = image

    def draw_scorelist(
        self,
        player_info: PlayerMaiInfo,
        scores: List[PlayerMaiScore],
        title: str,
        page: int = 1,
        page_size: int = 50,
    ) -> Image.Image:
        del player_info

        score_page = scores[(page - 1) * page_size : page * page_size]
        groups = max(1, math.ceil(len(score_page) / 20))
        height = 150 + groups * 576
        image = self._image.copy() if self._image is not None else build_maimai_background(1400, height)
        if image.height != height:
            image = build_maimai_background(1400, height)
        painter = MaimaiScorePainter(image)

        section_title(image, title, y=30, x=475, lengthen=True, size=28)
        for idx in range(groups):
            chunk = score_page[idx * 20 : (idx + 1) * 20]
            if not chunk:
                continue
            section_y = 30 + idx * 576
            if idx > 0:
                start = (page - 1) * page_size + idx * 20 + 1
                end = start + len(chunk) - 1
                section_title(image, f"No.{start} - No.{end}", y=section_y, x=475, lengthen=True, size=28)
            painter.draw_cards(chunk, 16, 140 + idx * 576)

        footer_design(image, f"Designed by Yuri-YuzuChaN & BlueDeer233. Generated by {BOT_LABEL}", bottom=113)
        return image

    def draw_rise(self, songs: RecommendSongs, min_dx_rating: int) -> Image.Image:
        left_count = len(songs.old_version)
        right_count = len(songs.new_version)
        row_count = max(left_count, right_count, 1)
        height = row_count * 140 + 110 + 150
        image = self._image.copy() if self._image is not None else build_maimai_background(1400, height)
        if image.height != height:
            image = build_maimai_background(1400, height)
        painter = MaimaiScorePainter(image)

        title_bg_path = PIC_DIR / "title.png"
        if title_bg_path.exists():
            title_bg = get_image(title_bg_path).resize((273, 80))
            image.alpha_composite(title_bg, (314, 30))
            image.alpha_composite(title_bg, (814, 30))
            painter._sy.draw(450, 68, 18, "旧版本谱面推荐", TEXT_COLOR, "mm")
            painter._sy.draw(950, 68, 18, "现行版本谱面推荐", TEXT_COLOR, "mm")
        else:
            section_title(image, "旧版本谱面推荐", y=30, x=314, lengthen=False, size=18)
            section_title(image, "现行版本谱面推荐", y=30, x=814, lengthen=False, size=18)

        for index, song in enumerate(songs.old_version):
            painter.draw_rise_card(200, 120 + index * 140, song, min_dx_rating)
        for index, song in enumerate(songs.new_version):
            painter.draw_rise_card(700, 120 + index * 140, song, min_dx_rating)

        footer_design(image, f"Designed by Yuri-YuzuChaN & BlueDeer233. Generated by {BOT_LABEL}", bottom=110, width=800)
        return image
