from __future__ import annotations

from typing import List

from PIL import Image, ImageDraw

from ..models.song import MaiSong
from ..score import PlayerMaiScore
from .render_core import (
    BOT_LABEL,
    PIC_DIR,
    SIYUAN,
    TBFONT,
    TEXT_COLOR,
    TITLE_COLORS,
    draw_rating_digits,
    dx_score_icon,
    footer_design,
    full_dx_score,
    genre_picture,
    get_image,
    music_picture,
    play_bonus_icon,
    rank_icon,
    safe_font,
    song_type_short,
    song_version_name,
    type_picture,
    version_picture,
)
from .utils import DrawText, change_column_width, coloum_width


def _score_map(scores: List[PlayerMaiScore]) -> dict[int, PlayerMaiScore]:
    return {score.song_difficulty.value: score for score in scores}


def _draw_player_song_info(song: MaiSong, scores: List[PlayerMaiScore]) -> Image.Image:
    image = get_image(PIC_DIR / "info_bg.png")
    draw = ImageDraw.Draw(image)
    tb = DrawText(draw, TBFONT)
    sy = DrawText(draw, SIYUAN)

    if (logo_path := PIC_DIR / "logo.png").exists():
        image.alpha_composite(get_image(logo_path).resize((249, 120)), (0, 34))

    cover = get_image(music_picture(song.id)).resize((300, 300))
    image.alpha_composite(cover, (100, 260))

    genre_path = genre_picture(song.genre)
    if genre_path is not None:
        image.alpha_composite(get_image(genre_path).resize((300, 300)), (100, 260))

    version_path = version_picture(song.version)
    if version_path is not None:
        image.alpha_composite(get_image(version_path).resize((183, 90)), (295, 205))

    song_type = scores[0].song_type.value if scores else ("dx" if song.difficulties.dx and not song.difficulties.standard else "standard")
    type_path = type_picture(song_type)
    if type_path is not None:
        image.alpha_composite(get_image(type_path).resize((55, 20)), (350, 560))

    artist = song.artist
    if coloum_width(artist) > 58:
        artist = change_column_width(artist, 57) + "..."
    sy.draw(255, 595, 12, artist, TEXT_COLOR, "mm")

    title = song.title
    if coloum_width(title) > 38:
        title = change_column_width(title, 37) + "..."
    sy.draw(255, 622, 18, title, TEXT_COLOR, "mm")
    tb.draw(160, 720, 22, song.id, TEXT_COLOR, "mm")
    tb.draw(380, 720, 22, song.bpm, TEXT_COLOR, "mm")

    diffs = song.difficulties.dx if song_type == "dx" else song.difficulties.standard
    score_by_diff = _score_map(scores)

    step_y = 100
    for num in range(max(5, len(diffs))):
        row_y = 235 + step_y * num
        tab_path = PIC_DIR / f"d-{num}.png"
        if tab_path.exists():
            image.alpha_composite(get_image(tab_path), (650, row_y))

        if num < len(diffs):
            tb.draw(685, 248 + step_y * num, 25, diffs[num].level_value, TEXT_COLOR, "mm")
        else:
            sy.draw(800, 302 + step_y * num, 30, "没有该难度", TEXT_COLOR, "mm")
            continue

        score = score_by_diff.get(num)
        if score is None:
            sy.draw(800, 302 + step_y * num, 30, "未游玩", TEXT_COLOR, "mm")
            continue

        ra_dx_path = PIC_DIR / "ra-dx.png"
        if ra_dx_path.exists():
            image.alpha_composite(get_image(ra_dx_path), (850, 272 + step_y * num))

        dx_icon = dx_score_icon(score, width=32, height=19)
        if dx_icon is not None:
            image.alpha_composite(dx_icon, (851, 296 + step_y * num))
        tb.draw(916, 304 + step_y * num, 13, f"{score.dx_score}/{full_dx_score(score)}", TEXT_COLOR, "mm")

        fcfs_path = PIC_DIR / "fcfs.png"
        if fcfs_path.exists():
            image.alpha_composite(get_image(fcfs_path), (965, 265 + step_y * num))

        fc_icon = play_bonus_icon(score.fc.value if score.fc else None)
        if fc_icon is not None:
            image.alpha_composite(fc_icon.resize((65, 65)), (960, 261 + step_y * num))

        fs_icon = play_bonus_icon(score.fs.value if score.fs else None)
        if fs_icon is not None:
            image.alpha_composite(fs_icon.resize((65, 65)), (1025, 261 + step_y * num))

        rank = rank_icon(score, width=100, height=45)
        if rank is not None:
            image.alpha_composite(rank, (737, 272 + step_y * num))

        tb.draw(510, 292 + step_y * num, 42, f"{score.achievements:.4f}%", TEXT_COLOR, "lm")
        tb.draw(915, 283 + step_y * num, 18, round(score.dx_rating), TEXT_COLOR, "mm")

    footer_design(image, f"Designed by Yuri-YuzuChaN & BlueDeer233. Generated by {BOT_LABEL}", bottom=95, width=900)
    return image


def _draw_static_song_info(song: MaiSong) -> Image.Image:
    image = get_image(PIC_DIR / "song_bg.png")
    draw = ImageDraw.Draw(image)
    tb = DrawText(draw, TBFONT)
    sy = DrawText(draw, SIYUAN)

    if (logo_path := PIC_DIR / "logo.png").exists():
        image.alpha_composite(get_image(logo_path).resize((249, 120)), (65, 25))

    cover = get_image(music_picture(song.id)).resize((280, 280))
    image.alpha_composite(cover, (110, 180))

    version_path = version_picture(song.version)
    if version_path is not None:
        image.alpha_composite(get_image(version_path).resize((182, 90)), (800, 370))

    title = song.title
    if coloum_width(title) > 40:
        title = change_column_width(title, 39) + "..."
    sy.draw(405, 220, 28, title, TEXT_COLOR, "lm")

    artist = song.artist
    if coloum_width(artist) > 50:
        artist = change_column_width(artist, 49) + "..."
    sy.draw(407, 265, 20, artist, TEXT_COLOR, "lm")
    tb.draw(460, 330, 30, song.bpm, TEXT_COLOR, "lm")
    tb.draw(405, 435, 28, f"ID {song.id}", TEXT_COLOR, "lm")
    sy.draw(665, 435, 24, song.genre, TEXT_COLOR, "mm")

    all_diffs = song.difficulties.standard if song.difficulties.standard else song.difficulties.dx
    for num, diff in enumerate(all_diffs[:5]):
        tb.draw(181, 610 + 73 * num, 30, f"{diff.level}({diff.level_value:.1f})", TITLE_COLORS[min(num, 4)], "mm")
        tb.draw(315, 600 + 73 * num, 30, f"{diff.level_fit:.2f}" if diff.level_fit else "-", TEXT_COLOR, "mm")
        notes = [diff.notes.tap, diff.notes.hold, diff.notes.slide, diff.notes.touch, diff.notes.break_]
        tb.draw(437, 600 + 73 * num, 30, sum(notes), TEXT_COLOR, "mm")
        for idx, value in enumerate(notes):
            tb.draw(556 + 119 * idx, 600 + 73 * num, 30, value, TEXT_COLOR, "mm")
        if num > 1:
            charter = diff.note_designer
            if coloum_width(charter) > 19:
                charter = change_column_width(charter, 18) + "..."
            sy.draw(372, 1030 + 47 * (num - 2), 18, charter, TEXT_COLOR, "mm")

    footer_design(image, f"Designed by Yuri-YuzuChaN & BlueDeer233. Generated by {BOT_LABEL}", bottom=105, width=900)
    return image


def draw_music_info(song: MaiSong, scores: List[PlayerMaiScore]) -> Image.Image:
    return _draw_player_song_info(song, scores) if scores else _draw_static_song_info(song)
