from __future__ import annotations

from typing import List

from PIL import Image, ImageDraw

from ..models.song import MaiSong
from ..score import PlayerMaiScore
from ._config import ACCENT_COLOR, DIFF_COLORS, FONT_MAIN, FONT_NUM, PANEL_BG, PANEL_BORDER, SUBTEXT_COLOR, TEXT_COLOR
from .utils import DrawText, change_column_width, coloum_width


def _score_rate_text(score: PlayerMaiScore) -> str:
    rate = score.rate.value.upper()
    if rate == "SP":
        return "S+"
    if rate == "SSP":
        return "SS+"
    if rate == "SSSP":
        return "SSS+"
    return rate


def _candidate_cover_paths(song_id: int):
    ids = [song_id, song_id + 10000]
    for sid in ids:
        yield f"{sid}.png"
        yield f"{sid:05d}.png"


def draw_music_info(song: MaiSong, scores: List[PlayerMaiScore]) -> Image.Image:
    image = Image.new("RGBA", (1400, 920), (245, 248, 255, 255))
    draw = ImageDraw.Draw(image)
    sy = DrawText(draw, FONT_MAIN)
    tb = DrawText(draw, FONT_NUM)

    draw.rounded_rectangle((24, 24, 1376, 896), radius=36, fill=PANEL_BG, outline=PANEL_BORDER, width=3)
    draw.rounded_rectangle((52, 52, 432, 432), radius=28, fill=(236, 241, 255, 255), outline=PANEL_BORDER, width=2)

    cover = None
    from ._config import COVER_DIR

    for filename in _candidate_cover_paths(song.id):
        path = COVER_DIR / filename
        if path.exists():
            cover = Image.open(path).convert("RGBA").resize((340, 340))
            break
    if cover is None:
        cover = Image.new("RGBA", (340, 340), (239, 243, 255, 255))
        cover_draw = ImageDraw.Draw(cover)
        cover_draw.rounded_rectangle((0, 0, 339, 339), radius=24, fill=(239, 243, 255, 255), outline=PANEL_BORDER, width=3)
        DrawText(cover_draw, FONT_NUM).draw(170, 170, 42, song.id, ACCENT_COLOR, "mm")
    image.alpha_composite(cover, (72, 72))

    title = song.title
    if coloum_width(title) > 36:
        title = change_column_width(title, 36) + "..."
    sy.draw(470, 92, 34, title, TEXT_COLOR, "lm")
    sy.draw(470, 138, 18, f"Artist: {song.artist}", SUBTEXT_COLOR, "lm")
    sy.draw(470, 170, 18, f"Genre: {song.genre}", SUBTEXT_COLOR, "lm")
    sy.draw(470, 202, 18, f"BPM: {song.bpm}", SUBTEXT_COLOR, "lm")
    sy.draw(470, 234, 18, f"Version: {song.version}", SUBTEXT_COLOR, "lm")
    tb.draw(470, 282, 20, f"Song ID {song.id}", ACCENT_COLOR, "lm")

    song_type = scores[0].song_type.value if scores else "standard"
    diffs = song.difficulties.dx if song_type == "dx" else song.difficulties.standard

    sy.draw(72, 460, 24, "Difficulty / Score Details", TEXT_COLOR, "lm")

    for index, diff in enumerate(diffs[:5]):
        y = 508 + index * 72
        score = next((item for item in scores if item.song_difficulty.value == index), None)
        diff_color = DIFF_COLORS[index]

        draw.rounded_rectangle((52, y, 1348, y + 56), radius=20, fill=(255, 255, 255, 220), outline=diff_color, width=2)
        draw.rounded_rectangle((64, y + 8, 182, y + 48), radius=18, fill=diff_color)
        sy.draw(123, y + 28, 18, f"Diff {index}", (255, 255, 255, 255), "mm")

        tb.draw(214, y + 28, 20, diff.level_value, diff_color, "lm")
        sy.draw(278, y + 28, 16, f"Level {diff.level}", SUBTEXT_COLOR, "lm")

        notes_total = diff.notes.total if diff.notes else 0
        sy.draw(426, y + 28, 16, f"Notes {notes_total}", SUBTEXT_COLOR, "lm")

        if score:
            rate_text = _score_rate_text(score)
            fcfs = [rate_text]
            if score.fc:
                fcfs.append(score.fc.value.upper())
            if score.fs:
                fcfs.append(score.fs.value.upper())
            status = " / ".join(fcfs)
            tb.draw(590, y + 28, 19, f"{score.achievements:.4f}%", diff_color, "lm")
            sy.draw(760, y + 28, 16, status, SUBTEXT_COLOR, "lm")
            tb.draw(980, y + 28, 17, f"DX {score.dx_score}", SUBTEXT_COLOR, "lm")
            tb.draw(1132, y + 28, 17, f"Ra {score.dx_rating}", ACCENT_COLOR, "lm")
            if score.play_count:
                sy.draw(1266, y + 28, 15, f"PC {score.play_count}", SUBTEXT_COLOR, "rm")
        else:
            sy.draw(590, y + 28, 18, "No record", SUBTEXT_COLOR, "lm")

    sy.draw(
        700,
        862,
        16,
        "Generated by SuzunoBot with embedded Nonebot-Plugin-Rikka maimai implementation",
        SUBTEXT_COLOR,
        "mm",
    )
    return image
